# Import the uuid module to generate unique identifiers
import uuid
# Import the models module from Django to define database models
from django.db import models

#Define a new model class called User that inherits from models.Model
class User(models.Model):
    pass

# Define a new model class called Product that inherits from models.Model
class Product(models.Model):
    # Define a character field for the product name with a maximum length of 200 characters
    name = models.CharField(max_length=200)
    # Define a text field for a detailed product description
    description = models.TextField()
    # Define a decimal field for the product price with up to 10 digits total and 2 decimal places
    price = models.DecimalField(max_digits=10, decimal_places=2)
    # Define a positive integer field for the quantity of the product in stock
    stock = models.PositiveIntegerField()
    # Define an image field for uploading a product image to the 'products/' directory, allowing it to be blank or null
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    # Decorator to define a property method
    @property
    # Define a method to check if the product is in stock
    def in_stock(self):
        #Return True if stock is greater than 0, otherwise return False
        return self.stock > 0
    
     # Define a string representation method for the Product model
    def __str__(self):
        # Return the name of the product as its string representation
        return self.name

#Define a new model class called Order that inherits from models.Model
class Order(models.Model):
     # Define a class for status choices using Django's TextChoices
    class StatusChoices(models.TextChoices):
        # Define a status choice for pending orders
        PENDING = 'Pending' 
        # Define a status choice for confirmed orders
        CONFIRMED = 'Confirmed' 
        # Define a status choice for cancelled orders 
        CANCELLED = 'Cancelled' 

    # Define a UUID field as the primary key with a default value generated by uuid4
    order_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    # Define a foreign key relationship to the User model; delete the order if the user is deleted
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Define a DateTime field that automatically sets the date and time when the order is created
    created_at = models.DateTimeField(auto_now_add=True)
     # Define a CharField for order status with choices from StatusChoices and a default value of PENDING
    status = models.CharField(max_length=10,choices=StatusChoices.choices,default=StatusChoices.PENDING)
    # This indicates that the model has a Many-to-Many relationship with the Product model
    # The (__through__) argument specifies an intermediary model that will be used to manage the Many-to-Many relationship.  In this case, the intermediary model is called OrderItem.
    # The (__related_name__) argument specifies the name to use for the reverse relation from the Product model back to the model that contains this Many-to-Many field.
    # This means that if you have a Product instance, you can access all related orders using 
    products = models.ManyToManyField(Product, through='OrderItem', related_name='orders')
    # Define a string representation method for the Order model
    def __str__(self):
         # Return a formatted string showing the order ID and the username of the user who placed the order
        return f"Order {self.order_id} by {self.user.username}"
    

#This defines a new model class called ItemOrder, which represents an item in an order. It inherits from models.Model, making it a Django model.
class ItemOrder(models.Model):
    #This creates a foreign key relationship to the Order model. If the related order is deleted, all associated ItemOrder instances will also be deleted due to the CASCADE behavior.
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    #This creates a foreign key relationship to the Product model
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    #his defines a field to store the quantity of the product in the order. It must be a positive integer, allowing for large quantities.
    quantity = models.PositiveBigIntegerField()

    #This decorator indicates that the following method is a property that can be accessed like an attribute
    @property
    #This method calculates the subtotal for this item order.
    def item_subtotal(self):
        # returns the subtotal by multiplying the price of the product by the quantity ordered.
        return self.product.price * self.quantity

    #This method defines how an instance of ItemOrder will be represented as a string.
    def __str__(self):
        # returns a formatted string that includes the quantity of the product, the product's name, and the order ID, providing a clear description of the item order.
        return f"{self.quantity} x {self.product.name} in Order {self.order.order_id}"   